# Generated by Django 2.1.7 on 2019-07-30 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(default='', max_length=128, verbose_name='情绪')),
                ('type', models.CharField(blank=True, choices=[('public', '通用音乐'), ('mainland', '大陆红歌'), ('taiwan', '台语歌'), ('japanese', '日语歌')], max_length=32, verbose_name='歌曲类型')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '歌单',
                'verbose_name_plural': '歌单',
                'ordering': ['create_time'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, verbose_name='歌曲名称')),
                ('artist', models.CharField(default='未知艺术家', max_length=128, verbose_name='艺术家')),
                ('url', models.CharField(default='', max_length=512, verbose_name='歌曲地址')),
                ('album_img', models.CharField(blank=True, default='', max_length=128, verbose_name='专辑封面')),
                ('artist_img', models.CharField(blank=True, default='', max_length=128, verbose_name='艺术家图片')),
                ('type', models.CharField(blank=True, choices=[('public', '通用音乐'), ('mainland', '大陆红歌'), ('taiwan', '台语歌'), ('japanese', '日语歌')], max_length=32, verbose_name='歌曲类型')),
                ('is_shelf', models.BooleanField(default=True, verbose_name='是否上架')),
                ('corpus_a', models.TextField(blank=True, default='', max_length=256, verbose_name='语料A')),
                ('corpus_b', models.TextField(blank=True, default='', max_length=256, verbose_name='语料B')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '歌曲',
                'verbose_name_plural': '歌曲',
                'ordering': ['create_time'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=128, verbose_name='姓')),
                ('last_name', models.CharField(blank=True, default='', max_length=128, verbose_name='名')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='邮件')),
                ('mobile', models.CharField(blank=True, default='', max_length=128, unique=True, verbose_name='电话')),
                ('baidu_id', models.CharField(blank=True, default='', max_length=128, unique=True, verbose_name='百度ID')),
                ('sex', models.CharField(blank=True, choices=[('male', '男'), ('female', '女')], default='男', max_length=32, verbose_name='性别')),
                ('is_delete', models.BooleanField(blank=True, default=False, verbose_name='是否删除')),
                ('note', models.TextField(blank=True, default='', max_length=256, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['create_time'],
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='song',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='timechick.Song', verbose_name='歌曲'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='timechick.User', verbose_name='用户'),
        ),
    ]
