# Generated by Django 2.1.7 on 2019-12-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timechick', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='baidu_id',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='百度ID'),
        ),
    ]
