# Generated by Django 2.1.7 on 2019-06-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timechick', '0003_auto_20190507_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='baidu_id',
        ),
        migrations.AlterField(
            model_name='song',
            name='album_img',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='专辑封面'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist_img',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='艺术家图片'),
        ),
        migrations.AlterField(
            model_name='song',
            name='type',
            field=models.CharField(blank=True, choices=[('public', '通用音乐'), ('mainland', '大陆红歌'), ('taiwan', '台语歌'), ('japanese', '日语歌')], max_length=32, verbose_name='歌曲类型'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=128, unique=True, verbose_name='电话'),
        ),
    ]
