# Generated by Django 2.1.7 on 2019-07-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timechick', '0004_auto_20190622_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='type',
            field=models.CharField(blank=True, choices=[('public', '通用音乐'), ('mainland', '大陆红歌'), ('taiwan', '台语歌'), ('japanese', '日语歌')], max_length=32, verbose_name='歌曲类型'),
        ),
    ]
